### ISSUE TITLE
Various buttons not working anymore

### ISSUE THREAD

**Issue by pittbull** [GMTrevis/Homeassistant-NodeRed-Systemair-VTR300#10]
New issues I recently discoverd: The following button dosen't seem to work anymore:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/1532149/199807441-a7cc6f67-e7f2-4992-8513-f253d47a77e1.png">

Any insight?

**Comment by pittbull** [comment]
The following is logged in the HA:

```
2022-11-03 19:42:57.617 INFO (MainThread) [homeassistant.components.script.vtr300_system_popup] vtr300_system_popup: Running script sequence
2022-11-03 19:42:57.617 INFO (MainThread) [homeassistant.components.script.vtr300_system_popup] vtr300_system_popup: Executing step call service
2022-11-03 19:42:57.618 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'deviceID' is undefined when rendering '{{ deviceID }}'
2022-11-03 19:42:58.919 INFO (MainThread) [homeassistant.components.script.vtr300_system_popup] vtr300_system_popup: Running script sequence
2022-11-03 19:42:58.919 INFO (MainThread) [homeassistant.components.script.vtr300_system_popup] vtr300_system_popup: Executing step call service
2022-11-03 19:42:58.919 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'deviceID' is undefined when rendering '{{ deviceID }}'
```

**Comment by pittbull** [comment]
Seems this started after the browser_mod update. Not sure how to fix it.

**Comment by Comiter** [comment]
You just need to update your scripts to match the new formatting for Browser_mod.
Replace data_template with data, and replace card with content. In addition deviceID has been replaced with browser_id, so you need to update the cards in the UI as well.

Below is the code for Frikjøling, where I have made the modifications as a reference.

Modified script for frikjøling:

```
#------------------------------ VTR300 Frikjøling Popup ---------------------------|
vtr300_frecooling_popup:
  sequence:
    - service: browser_mod.popup
      data:
        deviceID: "{{ browser_id }}"
        title: Frikjøling/Nattkjøling
        content:
          type: entities
          entities:
            - entity: sensor.vtr300_freecooling_state
            - entity: input_number.vtr300_freecooling_start_outdoor_daytime_min_temp
            - entity: input_number.vtr300_freecooling_stop_outdoor_temp_hi_sp
              name: Utetemp. høy grense
            - entity: input_number.vtr300_freecooling_stop_outdoor_temp_lo_sp
              name: Utetemp. lav grense
            - entity: input_number.vtr300_freecooling_stop_extractair_temp_lo_sp
              name: Avtrekk lav grense
            - entity: input_datetime.vtr300_freecool_night_prd_start_sp
            - entity: input_datetime.vtr300_freecool_night_prd_end_sp
            - entity: input_select.vtr300_freecooling_supply_fan_level_set
              icon: 'mdi:weather-windy'
            - entity: input_select.vtr300_freecooling_extract_fan_level_set
              icon: 'mdi:weather-windy'
```

Modified code for button in vertical stack card:

```
type: custom:button-card
color: grey
name: Frikjøling
icon: mdi:tools
aspect_ratio: 1.5
show_state: false
tap_action:
  action: fire-dom-event
  browser_mod:
    command: call-service
    service: script.vtr300_frecooling_popup
    data:
      browser_id: this
styles:
  card:
    - font-size: 12px
    - filter: opacity(80%)
    - '--mdc-ripple-color': yellow
    - '--mdc-ripple-press-opacity': 0.5
  grid:
    - grid-template-areas: '"i" "n" "s"'
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content
  img_cell:
    - align-self: start
    - text-align: start
  name:
    - justify-self: middle
    - padding-left: 0px
    - font-weight: ''
  state:
    - justify-self: start
    - padding-left: 10px
  label:
    - font-size: 11px
state:
  - value: 'off'
    styles:
      card:
        - filter: opacity(50%)
      icon:
        - filter: grayscale(100%)
show_label: false
size: 80%
```
